"""CLI commands for strategy management.

Provides ``list``, ``validate``, and ``scaffold`` sub-commands.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Optional

import typer

strategy_app = typer.Typer(
    help="Strategy management commands",
    no_args_is_help=True,
)


# ---------------------------------------------------------------------------
# list
# ---------------------------------------------------------------------------
@strategy_app.command("list")
def strategy_list(
    json_output: bool = typer.Option(False, "--json", help="Output as JSON"),
) -> None:
    """List all available strategies (built-in and user-defined)."""
    from clawquant.core.runtime.loader import list_strategies
    from clawquant.core.utils.output import print_result, print_table

    # Check global JSON mode from shared state
    from clawquant.core.utils.state import get_json_mode
    is_json = json_output or get_json_mode()

    strategies = list_strategies()

    if is_json:
        data = [s.model_dump(mode="json") for s in strategies]
        print_result(data, json_mode=True)
        return

    rows = [
        (s.name, s.version, s.description[:60], ", ".join(s.tags))
        for s in strategies
    ]
    print_table(
        headers=["Name", "Version", "Description", "Tags"],
        rows=rows,
        title="Available Strategies",
    )


# ---------------------------------------------------------------------------
# validate
# ---------------------------------------------------------------------------
@strategy_app.command("validate")
def strategy_validate(
    name: Optional[str] = typer.Option(None, "--name", "-n", help="Strategy name to validate"),
    file: Optional[str] = typer.Option(None, "--file", "-f", help="Path to strategy .py file"),
) -> None:
    """Validate a strategy against the BaseStrategy interface."""
    from clawquant.core.runtime.loader import (
        discover_strategies,
        load_strategy,
        validate_strategy,
    )

    if name is None and file is None:
        typer.echo("Error: provide either --name or --file", err=True)
        raise typer.Exit(code=1)

    # Resolve strategy class
    if file is not None:
        filepath = Path(file)
        if not filepath.is_file():
            typer.echo(f"Error: file not found: {filepath}", err=True)
            raise typer.Exit(code=1)
        # Use loader's file: protocol to import
        from clawquant.core.runtime.loader import _import_module_from_file, _find_strategy_classes

        mod = _import_module_from_file(filepath)
        if mod is None:
            typer.echo(f"Error: failed to import {filepath}", err=True)
            raise typer.Exit(code=1)
        classes = _find_strategy_classes(mod)
        if not classes:
            typer.echo(f"Error: no BaseStrategy subclass found in {filepath}", err=True)
            raise typer.Exit(code=1)
        strategy_cls = classes[0]
    else:
        strategies = discover_strategies()
        if name not in strategies:
            available = ", ".join(sorted(strategies.keys())) or "(none)"
            typer.echo(f"Error: strategy '{name}' not found. Available: {available}", err=True)
            raise typer.Exit(code=1)
        strategy_cls = strategies[name]

    # Run validation
    result = validate_strategy(strategy_cls)

    # Display results
    try:
        cls_name = strategy_cls.metadata().name
    except Exception:
        cls_name = strategy_cls.__name__

    if result["valid"]:
        typer.echo(f"[PASS] Strategy '{cls_name}' passed all validation checks.")
    else:
        typer.echo(f"[FAIL] Strategy '{cls_name}' has validation errors:")

    for err in result["errors"]:
        typer.echo(f"  ERROR: {err}")
    for warn in result["warnings"]:
        typer.echo(f"  WARNING: {warn}")

    if not result["valid"]:
        raise typer.Exit(code=1)


# ---------------------------------------------------------------------------
# scaffold
# ---------------------------------------------------------------------------
_SCAFFOLD_TEMPLATE = textwrap.dedent('''\
    """Custom strategy: {name}.

    Generated by ClawQuant Trader scaffold command.
    自定义策略模板，由 ClawQuant Trader scaffold 命令生成。
    """

    from __future__ import annotations

    from typing import List

    import pandas as pd

    from clawquant.core.runtime.base_strategy import BaseStrategy
    from clawquant.core.runtime.models import MarketState, PortfolioState, StrategyMetadata


    class {class_name}(BaseStrategy):
        """{name} strategy."""

        # ------------------------------------------------------------------
        # 1. metadata() — 策略元信息 / Strategy metadata
        #    Define name, version, description, parameter JSON Schema, and tags.
        #    定义策略名称、版本、描述、参数 JSON Schema 和标签。
        # ------------------------------------------------------------------
        @classmethod
        def metadata(cls) -> StrategyMetadata:
            return StrategyMetadata(
                name="{name}",
                version="0.1.0",
                description="TODO: describe your strategy. / 请描述你的策略。",
                params_schema={{
                    "type": "object",
                    "properties": {{
                        "example_param": {{
                            "type": "number",
                            "description": "An example parameter. / 示例参数。",
                            "default": 1.0,
                        }},
                    }},
                }},
                tags=["custom"],
            )

        # ------------------------------------------------------------------
        # 2. compute_indicators() — 计算技术指标 / Compute technical indicators
        #    Add indicator columns to df. All column names MUST be prefixed
        #    with your strategy name to avoid conflicts.
        #    向 df 添加指标列。列名必须以策略名为前缀，避免冲突。
        #
        #    ⚠ Common mistake / 常见错误:
        #      - Forgetting df = df.copy() — this modifies the original data!
        #        忘记 df.copy() 会修改原始数据！
        #      - Using column names without prefix (e.g. "rsi" instead of
        #        "my_strategy_rsi") — will conflict with other strategies!
        #        列名不带前缀会和其他策略冲突！
        # ------------------------------------------------------------------
        def compute_indicators(self, df: pd.DataFrame, params: dict) -> pd.DataFrame:
            df = df.copy()
            # TODO: add indicator columns prefixed with "{name}_"
            # Example / 示例:
            #   period = params.get("example_param", 14)
            #   df["{name}_sma"] = df["close"].rolling(window=int(period)).mean()
            return df

        # ------------------------------------------------------------------
        # 3. generate_signals() — 生成交易信号 / Generate trading signals
        #    Return a pd.Series with values in {{-1, 0, 1}}.
        #    返回值为 {{-1, 0, 1}} 的 pd.Series。
        #      1 = BUY / 买入,  0 = HOLD / 持有,  -1 = SELL / 卖出
        #
        #    ⚠ Common mistake / 常见错误:
        #      - Returning float instead of int — use .astype(int)
        #        返回 float 而非 int，请用 .astype(int)
        #      - Not setting NaN indicator rows to 0 — causes errors in backtest!
        #        指标为 NaN 的行没设为 0，回测会报错！
        # ------------------------------------------------------------------
        def generate_signals(self, df: pd.DataFrame, params: dict) -> pd.Series:
            # TODO: implement signal logic / 实现信号逻辑
            # Example / 示例:
            #   if "{name}_sma" not in df.columns:
            #       df = self.compute_indicators(df, params)
            #   signals = pd.Series(0, index=df.index, dtype=int)
            #   signals[df["close"] > df["{name}_sma"]] = 1
            #   signals[df["close"] < df["{name}_sma"]] = -1
            #   signals[df["{name}_sma"].isna()] = 0
            #   return signals
            return pd.Series(0, index=df.index, dtype=int)

        # ------------------------------------------------------------------
        # 4. position_sizing() — 仓位管理 / Position sizing
        #    Return target position change in USDT (positive=buy, negative=sell).
        #    返回仓位变动金额（正=买入，负=卖出），单位 USDT。
        #
        #    ⚠ Common mistake / 常见错误:
        #      - Buying more than available cash — check portfolio_state.cash!
        #        买入金额超过可用现金，请检查 portfolio_state.cash！
        #      - Selling more than position value — check position_values!
        #        卖出金额超过持仓价值！
        # ------------------------------------------------------------------
        def position_sizing(
            self,
            signal: int,
            portfolio_state: PortfolioState,
            params: dict,
        ) -> float:
            if signal == 0:
                return 0.0
            # TODO: implement position sizing / 实现仓位计算
            # Example / 示例:
            #   pct = params.get("position_pct", 0.1)
            #   equity = portfolio_state.equity
            #   if signal == 1:
            #       return min(equity * pct, portfolio_state.cash)
            #   elif signal == -1:
            #       pos_val = sum(portfolio_state.position_values.values())
            #       return -min(pos_val * pct, pos_val)
            return 0.0

        # ------------------------------------------------------------------
        # 5. risk_controls() — 风险控制 / Risk controls
        #    Return list of dicts with "action" and "reason".
        #    返回包含 "action" 和 "reason" 的字典列表。
        #    Actions / 可选动作: "NONE", "REDUCE", "FLATTEN", "SKIP"
        # ------------------------------------------------------------------
        def risk_controls(
            self,
            portfolio_state: PortfolioState,
            market_state: MarketState,
            params: dict,
        ) -> List[dict]:
            # TODO: implement risk controls / 实现风险控制
            # Example / 示例:
            #   pos_val = sum(portfolio_state.position_values.values())
            #   if portfolio_state.equity > 0 and pos_val / portfolio_state.equity > 0.9:
            #       return [{{"action": "REDUCE", "reason": "Position > 90% of equity"}}]
            return [{{"action": "NONE", "reason": "No risk controls implemented yet."}}]

        # ------------------------------------------------------------------
        # 6. explain() — 解释说明 / Explain last action
        #    Return dict with "reasons" (List[str]) and "key_metrics" (Dict).
        #    返回包含 "reasons"（原因列表）和 "key_metrics"（关键指标）的字典。
        # ------------------------------------------------------------------
        def explain(self, last_state: dict) -> dict:
            return {{
                "reasons": ["TODO: explain last action / 请解释上次操作"],
                "key_metrics": {{}},
            }}
''')


@strategy_app.command("scaffold")
def strategy_scaffold(
    name: str = typer.Option(..., "--name", "-n", help="Strategy name (snake_case)"),
    output: str = typer.Option(".", "--output", "-o", help="Output directory"),
) -> None:
    """Generate a template strategy file."""
    # Build class name from snake_case
    class_name = "".join(word.capitalize() for word in name.split("_")) + "Strategy"
    content = _SCAFFOLD_TEMPLATE.format(name=name, class_name=class_name)

    out_dir = Path(output)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{name}.py"

    out_file.write_text(content, encoding="utf-8")
    typer.echo(f"Strategy scaffold written to: {out_file.resolve()}")
