"""CLI commands for strategy management.

Provides ``list``, ``validate``, and ``scaffold`` sub-commands.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Optional

import typer

strategy_app = typer.Typer(
    help="Strategy management commands",
    no_args_is_help=True,
)


# ---------------------------------------------------------------------------
# list
# ---------------------------------------------------------------------------
@strategy_app.command("list")
def strategy_list(
    json_output: bool = typer.Option(False, "--json", help="Output as JSON"),
) -> None:
    """List all available strategies (built-in and user-defined)."""
    from clawquant.core.runtime.loader import list_strategies
    from clawquant.core.utils.output import print_result, print_table

    # Check global JSON mode from shared state
    from clawquant.core.utils.state import get_json_mode
    is_json = json_output or get_json_mode()

    strategies = list_strategies()

    if is_json:
        data = [s.model_dump(mode="json") for s in strategies]
        print_result(data, json_mode=True)
        return

    rows = [
        (s.name, s.version, s.description[:60], ", ".join(s.tags))
        for s in strategies
    ]
    print_table(
        headers=["Name", "Version", "Description", "Tags"],
        rows=rows,
        title="Available Strategies",
    )


# ---------------------------------------------------------------------------
# validate
# ---------------------------------------------------------------------------
@strategy_app.command("validate")
def strategy_validate(
    name: Optional[str] = typer.Option(None, "--name", "-n", help="Strategy name to validate"),
    file: Optional[str] = typer.Option(None, "--file", "-f", help="Path to strategy .py file"),
) -> None:
    """Validate a strategy against the BaseStrategy interface."""
    from clawquant.core.runtime.loader import (
        discover_strategies,
        load_strategy,
        validate_strategy,
    )

    if name is None and file is None:
        typer.echo("Error: provide either --name or --file", err=True)
        raise typer.Exit(code=1)

    # Resolve strategy class
    if file is not None:
        filepath = Path(file)
        if not filepath.is_file():
            typer.echo(f"Error: file not found: {filepath}", err=True)
            raise typer.Exit(code=1)
        # Use loader's file: protocol to import
        from clawquant.core.runtime.loader import _import_module_from_file, _find_strategy_classes

        mod = _import_module_from_file(filepath)
        if mod is None:
            typer.echo(f"Error: failed to import {filepath}", err=True)
            raise typer.Exit(code=1)
        classes = _find_strategy_classes(mod)
        if not classes:
            typer.echo(f"Error: no BaseStrategy subclass found in {filepath}", err=True)
            raise typer.Exit(code=1)
        strategy_cls = classes[0]
    else:
        strategies = discover_strategies()
        if name not in strategies:
            available = ", ".join(sorted(strategies.keys())) or "(none)"
            typer.echo(f"Error: strategy '{name}' not found. Available: {available}", err=True)
            raise typer.Exit(code=1)
        strategy_cls = strategies[name]

    # Run validation
    result = validate_strategy(strategy_cls)

    # Display results
    try:
        cls_name = strategy_cls.metadata().name
    except Exception:
        cls_name = strategy_cls.__name__

    if result["valid"]:
        typer.echo(f"[PASS] Strategy '{cls_name}' passed all validation checks.")
    else:
        typer.echo(f"[FAIL] Strategy '{cls_name}' has validation errors:")

    for err in result["errors"]:
        typer.echo(f"  ERROR: {err}")
    for warn in result["warnings"]:
        typer.echo(f"  WARNING: {warn}")

    if not result["valid"]:
        raise typer.Exit(code=1)


# ---------------------------------------------------------------------------
# scaffold
# ---------------------------------------------------------------------------
_SCAFFOLD_TEMPLATE = textwrap.dedent('''\
    """Custom strategy: {name}.

    Generated by ClawQuant Trader scaffold command.
    """

    from __future__ import annotations

    from typing import List

    import pandas as pd

    from clawquant.core.runtime.base_strategy import BaseStrategy
    from clawquant.core.runtime.models import MarketState, PortfolioState, StrategyMetadata


    class {class_name}(BaseStrategy):
        """{name} strategy."""

        @classmethod
        def metadata(cls) -> StrategyMetadata:
            return StrategyMetadata(
                name="{name}",
                version="0.1.0",
                description="TODO: describe your strategy.",
                params_schema={{
                    "type": "object",
                    "properties": {{
                        "example_param": {{
                            "type": "number",
                            "description": "An example parameter.",
                            "default": 1.0,
                        }},
                    }},
                }},
                tags=["custom"],
            )

        def compute_indicators(self, df: pd.DataFrame, params: dict) -> pd.DataFrame:
            df = df.copy()
            # TODO: add indicator columns prefixed with "{name}_"
            return df

        def generate_signals(self, df: pd.DataFrame, params: dict) -> pd.Series:
            # TODO: implement signal logic returning {{-1, 0, 1}}
            return pd.Series(0, index=df.index, dtype=int)

        def position_sizing(
            self,
            signal: int,
            portfolio_state: PortfolioState,
            params: dict,
        ) -> float:
            if signal == 0:
                return 0.0
            # TODO: implement position sizing
            return 0.0

        def risk_controls(
            self,
            portfolio_state: PortfolioState,
            market_state: MarketState,
            params: dict,
        ) -> List[dict]:
            # TODO: implement risk controls
            return [{{"action": "NONE", "reason": "No risk controls implemented yet."}}]

        def explain(self, last_state: dict) -> dict:
            return {{
                "reasons": ["TODO: explain last action"],
                "key_metrics": {{}},
            }}
''')


@strategy_app.command("scaffold")
def strategy_scaffold(
    name: str = typer.Option(..., "--name", "-n", help="Strategy name (snake_case)"),
    output: str = typer.Option(".", "--output", "-o", help="Output directory"),
) -> None:
    """Generate a template strategy file."""
    # Build class name from snake_case
    class_name = "".join(word.capitalize() for word in name.split("_")) + "Strategy"
    content = _SCAFFOLD_TEMPLATE.format(name=name, class_name=class_name)

    out_dir = Path(output)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{name}.py"

    out_file.write_text(content, encoding="utf-8")
    typer.echo(f"Strategy scaffold written to: {out_file.resolve()}")
