"""Markdown report generation."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List


def generate_markdown_report(
    run_dir: Path,
    metrics: Dict[str, float],
    score: Dict[str, float],
    run_meta: dict,
    trades: List[dict],
) -> Path:
    """Generate a Markdown report.

    Args:
        run_dir: Directory to write the report to.
        metrics: Performance metrics dict.
        score: Stability score breakdown.
        run_meta: Run metadata dict.
        trades: List of trade dicts.

    Returns:
        Path to the generated Markdown report.
    """
    strat = run_meta.get("strategy", {})
    data = run_meta.get("data", {})
    config = run_meta.get("config", {})
    run_id = run_meta.get("run_id", "unknown")

    lines = [
        f"# Backtest Report: {run_id}",
        "",
        f"**Generated**: {run_meta.get('timestamp', 'N/A')}",
        "",
        "## Strategy",
        "",
        f"- **Name**: {strat.get('name', 'N/A')}",
        f"- **Version**: {strat.get('version', 'N/A')}",
        f"- **Params**: `{strat.get('params', {})}`",
        "",
        "## Data",
        "",
        f"- **Symbol**: {data.get('symbol', 'N/A')}",
        f"- **Interval**: {data.get('interval', 'N/A')}",
        f"- **Period**: {data.get('start', 'N/A')} → {data.get('end', 'N/A')}",
        f"- **Bars**: {data.get('bar_count', 0)}",
        f"- **Source**: {data.get('source', 'N/A')}",
        "",
        "## Configuration",
        "",
        f"- **Initial Capital**: ${config.get('initial_capital', 10000):.2f}",
        f"- **Fee**: {config.get('fee_bps', 10)} bps",
        f"- **Slippage**: {config.get('slippage_bps', 5)} bps",
        f"- **Fill Model**: {config.get('fill_model', 'next_open')}",
        "",
        "## Performance Metrics",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total Return | ${metrics.get('total_return', 0):.2f} ({metrics.get('total_return_pct', 0):.2f}%) |",
        f"| Annualized Return | {metrics.get('annualized_return', 0):.2f}% |",
        f"| Annualized Volatility | {metrics.get('annualized_volatility', 0):.2f}% |",
        f"| Sharpe Ratio | {metrics.get('sharpe_ratio', 0):.4f} |",
        f"| Sortino Ratio | {metrics.get('sortino_ratio', 0):.4f} |",
        f"| Calmar Ratio | {metrics.get('calmar_ratio', 0):.4f} |",
        f"| Max Drawdown | ${metrics.get('max_drawdown', 0):.2f} ({metrics.get('max_drawdown_pct', 0):.2f}%) |",
        f"| Win Rate | {metrics.get('win_rate', 0):.2f}% |",
        f"| Profit Factor | {metrics.get('profit_factor', 0):.4f} |",
        f"| Total Trades | {metrics.get('total_trades', 0)} |",
        f"| Avg Trade PnL | ${metrics.get('avg_trade_pnl', 0):.2f} |",
        f"| Avg Bars Held | {metrics.get('avg_bars_held', 0):.1f} |",
        f"| Expectancy | ${metrics.get('expectancy', 0):.2f} |",
        "",
        "## Stability Score",
        "",
        f"**Overall: {score.get('total', 0):.1f} / 100**",
        "",
        "| Dimension | Weight | Score |",
        "|-----------|--------|-------|",
        f"| Quality | 30% | {score.get('quality', 0):.1f} |",
        f"| Risk | 30% | {score.get('risk', 0):.1f} |",
        f"| Robustness | 20% | {score.get('robustness', 0):.1f} |",
        f"| Cost Sensitivity | 10% | {score.get('cost_sensitivity', 0):.1f} |",
        f"| Overtrade | 10% | {score.get('overtrade', 0):.1f} |",
        "",
    ]

    # Trade table (top 20)
    if trades:
        lines.extend([
            "## Trades (Recent)",
            "",
            "| # | Entry | Exit | Side | Entry Price | Exit Price | PnL | PnL% |",
            "|---|-------|------|------|-------------|------------|-----|------|",
        ])
        for i, t in enumerate(trades[:20], 1):
            entry_time = str(t.get("entry_time", ""))[:16]
            exit_time = str(t.get("exit_time", ""))[:16]
            lines.append(
                f"| {i} | {entry_time} | {exit_time} | {t.get('side', '')} "
                f"| {t.get('entry_price', 0):.2f} | {t.get('exit_price', 0):.2f} "
                f"| {t.get('pnl', 0):.2f} | {t.get('pnl_pct', 0):.2f}% |"
            )
        if len(trades) > 20:
            lines.append(f"\n*... and {len(trades) - 20} more trades*")
        lines.append("")

    # Charts reference
    lines.extend([
        "## Charts",
        "",
        "![Equity Curve](equity.png)",
        "",
        "![Drawdown](drawdown.png)",
        "",
        "![Trades](trades.png)",
        "",
        "---",
        f"*Report generated by ClawQuant Trader v{run_meta.get('environment', {}).get('engine_version', '0.1.0')}*",
    ])

    report_path = run_dir / "report.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path
